name: my-repo
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.pl.outputs.paths }}
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v3

      - name: Fetch action
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "changes"
          type: ".txt"
  example_matrix:
    needs: list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["changes/file1.txt","changes/files.txt"]
        os: [ubuntu-22.04, ubuntu-20.04]
    steps:
        - name: echo
          run: |
             echo ${{ matrix.version }} ${{ matrix.os }}
        
